#!/usr/bin/env python3
"""
Convert the MSDOS port's 8x8 CGA-2bpp font (msdos/src/ascii.c) into a
CoCo 3 2bpp tile array.  The CoCo 3 screen is 4bpp; hires_putc expands
each 2bpp pixel via text_palette[4] at render time, so this header keeps
the source 2bpp form unchanged (16 bytes/char) and lets us recolor text
by changing the palette.

Input:  msdos/src/ascii.c  -- C array  unsigned char ascii[256][16]
        Each glyph is 8 rows x 2 bytes/row, 4 pixels per byte (2bpp).

Output: coco/src/charset_coco3.h
        const unsigned char charset_coco3[N][16]
"""
import re, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC  = os.path.join(ROOT, "msdos", "src", "ascii.c")
DST  = os.path.join(ROOT, "coco", "src", "charset_coco3.h")

# Highest codepoint emitted (exclusive bound is N_GLYPHS).  0xD1 is the
# largest CP437 char used by the weather display (forecast separator).
N_GLYPHS = 0xD2

with open(SRC, "r") as f:
    text = f.read()

entries = re.findall(r'\{([^}]+)\}', text)
glyphs  = []
for e in entries[:N_GLYPHS]:
    bs = [int(b, 16) for b in re.findall(r'0x[0-9A-Fa-f]+', e)]
    bs = (bs + [0]*16)[:16]
    glyphs.append(bs)

while len(glyphs) < N_GLYPHS:
    glyphs.append([0]*16)

with open(DST, "w") as f:
    f.write("/* Generated by coco/support/cvt_msdos_font.py - do not edit. */\n")
    f.write(f"/* {N_GLYPHS} glyphs x 8 rows x 2 bytes/row, CGA 2bpp.\n"
            " * hires_putc expands each 2bpp pixel via text_palette[] at\n"
            " * render time. */\n\n")
    f.write("#ifndef CHARSET_COCO3_H\n#define CHARSET_COCO3_H\n\n")
    f.write(f"#define CHARSET_COCO3_N {N_GLYPHS}\n\n")
    f.write(f"static const unsigned char charset_coco3[{N_GLYPHS}][16] = {{\n")
    for idx, g in enumerate(glyphs):
        hex_bytes = ", ".join(f"0x{b:02X}" for b in g)
        f.write(f"    /* 0x{idx:02X} */ {{ {hex_bytes} }},\n")
    f.write("};\n\n#endif\n")

print(f"wrote {DST} ({len(glyphs)} glyphs, {len(glyphs)*16} bytes)")
